# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%= ENV['JOSEPHJABER_DEV_DATABASE'] %>
  username: <%= ENV['JOSEPHJABER_DEV_USER'] %>
  password: <%= ENV['JOSEPHJABER_DEV_PASSWORD'] %>
  host: <%= ENV['JOSEPHJABER_DEV_HOST'] %>
  port: <%= ENV['JOSEPHJABER_DEV_PORT'] %>
